(function(){
  const css = `#searchBox{position:fixed;left:12px;top:76px;z-index:9999;background:rgba(10,20,35,0.95);padding:8px;border-radius:8px;border:1px solid #1f3a52;color:#fff;width:320px;font:13px/1.2 Inter,system-ui}#searchBox input{width:100%;padding:6px;border-radius:6px;border:1px solid #29445f;background:#071726;color:#fff}#searchResults{max-height:320px;overflow:auto;margin-top:8px}#searchResults .item{padding:8px;border-bottom:1px solid #12273a;cursor:pointer}#searchResults .muted{color:#9db5cd;font-size:12px}`;
  const style=document.createElement('style');style.innerHTML=css;document.head.appendChild(style);
  const box=document.createElement('div');box.id='searchBox';box.innerHTML=`<input id="searchInput" placeholder="Поиск: адрес, ТК, дом, участок..."><div style="display:flex;gap:8px;margin-top:6px"><select id="searchType"><option value="all">Все</option><option value="house">Дом</option><option value="node">Узел</option><option value="pipe">Участок</option></select><button id="searchBtn">Найти</button></div><div id="searchResults"></div>`;
  document.body.appendChild(box);
  const inp=document.getElementById('searchInput'),btn=document.getElementById('searchBtn'),typeSel=document.getElementById('searchType'),resDiv=document.getElementById('searchResults');
  let timer=null; function doSearch(){const q=inp.value.trim(); if(!q){resDiv.innerHTML='';return;} fetch(`/api/search?q=${encodeURIComponent(q)}&type=${encodeURIComponent(typeSel.value)}`).then(r=>r.json()).then(j=>{
    const out=[]; if(j.houses && j.houses.length){ for(const h of j.houses){ out.push({kind:'house',title:`Дом ${h.street||''} ${h.house||''}`.trim(),sub:`TK: ${h.tk||''} · Узел: ${h.node? h.node.id:'—'}`,data:h}); }} if(j.nodes && j.nodes.length){ for(const n of j.nodes){ out.push({kind:'node',title:`Узел ${n.name||n.id}`,sub:`${n.type||''} · ${n.id}`,data:n}); }} if(j.pipes && j.pipes.length){ for(const p of j.pipes){ out.push({kind:'pipe',title:`Участок ${p.name||p.id}`,sub:`${p.id}`,data:p}); }} resDiv.innerHTML=''; if(out.length===0){resDiv.innerHTML='<div class="muted">Ничего не найдено</div>';return;} for(const it of out.slice(0,200)){const el=document.createElement('div');el.className='item';el.innerHTML=`<div style="font-weight:600">${it.title}</div><div class="muted">${it.sub}</div>`;el.onclick=()=>handleSelect(it);resDiv.appendChild(el);} }).catch(e=>{resDiv.innerHTML='<div class="muted">Ошибка поиска</div>';console.error(e)});
  }
  function handleSelect(item){ if(item.kind==='house'){ const h=item.data; if(h.node && h.node.lon && h.node.lat){ map.flyTo([h.node.lat,h.node.lon],17); highlightNode(h.node.id); } else if(h.geometry && h.geometry.coordinates){ const c=h.geometry.coordinates; map.flyTo([c[1],c[0]],17); } else alert('Координаты дома не найдены'); }
    else if(item.kind==='node'){ const n=item.data; if(n.lat && n.lon){ map.flyTo([n.lat,n.lon],17); highlightNode(n.id); } }
    else if(item.kind==='pipe'){ const p=item.data; try{ const coords=JSON.parse(p.coordinates); const geo=L.polyline(coords.map(c=>[c[1],c[0]]),{color:'#ff5722',weight:6,opacity:0.9}).addTo(map); map.fitBounds(geo.getBounds(),{padding:[40,40]}); setTimeout(()=>map.removeLayer(geo),8000); }catch(e){console.error(e);}
  }
  function highlightNode(nodeId){ fetch('/api/passports/node/'+encodeURIComponent(nodeId)).then(r=>r.json()).then(j=>{ const n=j.node; const pts=[ [n.lat,n.lon] ]; const m=L.circleMarker(pts[0],{radius:10,color:'#f59e0b',weight:3}).addTo(map); setTimeout(()=>map.removeLayer(m),6000); if(j.pipes && j.pipes.length){ for(const p of j.pipes){ try{ const coords=JSON.parse(p.coordinates); const line=L.polyline(coords.map(c=>[c[1],c[0]]),{color:'#f59e0b',weight:4,opacity:0.6}).addTo(map); setTimeout(()=>map.removeLayer(line),6000); }catch(e){} } } }).catch(console.error);
  }
  inp.addEventListener('input',()=>{clearTimeout(timer); timer=setTimeout(doSearch,350)}); btn.addEventListener('click',doSearch);
})();
